from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from coding_encouragement.models import Quote

class Command(BaseCommand):
    help = 'Load sample quotes into the database'

    def handle(self, *args, **options):
        # Get or create admin user for sample quotes
        admin_user, created = User.objects.get_or_create(
            username='admin',
            defaults={'email': 'admin@example.com', 'is_staff': True, 'is_superuser': True}
        )

        sample_quotes = [
            # Original 30 quotes
            {'text': 'The only way to do great work is to love what you do.', 'author': 'Steve Jobs'},
            {'text': 'Code is like humor. When you have to explain it, it\'s bad.', 'author': 'Cory House'},
            {'text': 'First, solve the problem. Then, write the code.', 'author': 'John Johnson'},
            {'text': 'Experience is the name everyone gives to their mistakes.', 'author': 'Oscar Wilde'},
            {'text': 'In order to be irreplaceable, one must always be different.', 'author': 'Coco Chanel'},
            {'text': 'Programming isn\'t about what you know; it\'s about what you can figure out.', 'author': 'Chris Pine'},
            {'text': 'The best error message is the one that never shows up.', 'author': 'Thomas Fuchs'},
            {'text': 'Simplicity is the ultimate sophistication.', 'author': 'Leonardo da Vinci'},
            {'text': 'Before software can be reusable it first has to be usable.', 'author': 'Ralph Johnson'},
            {'text': 'Make it work, make it right, make it fast.', 'author': 'Kent Beck'},
            {'text': 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'author': 'Martin Fowler'},
            {'text': 'Programming is not about typing, it\'s about thinking.', 'author': 'Rich Hickey'},
            {'text': 'The most important property of a program is whether it accomplishes the intention of its user.', 'author': 'C.A.R. Hoare'},
            {'text': 'Debugging is twice as hard as writing the code in the first place.', 'author': 'Brian Kernighan'},
            {'text': 'There are only two kinds of languages: the ones people complain about and the ones nobody uses.', 'author': 'Bjarne Stroustrup'},
            {'text': 'It\'s not a bug; it\'s an undocumented feature.', 'author': 'Anonymous'},
            {'text': 'The best way to get a project done faster is to start sooner.', 'author': 'Jim Highsmith'},
            {'text': 'Code never lies, comments sometimes do.', 'author': 'Ron Jeffries'},
            {'text': 'Programming is learned by writing programs.', 'author': 'Brian Kernighan'},
            {'text': 'The computer was born to solve problems that did not exist before.', 'author': 'Bill Gates'},
            {'text': 'Software is a great combination between artistry and engineering.', 'author': 'Bill Gates'},
            {'text': 'Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.', 'author': 'Patrick McKenzie'},
            {'text': 'The only way to learn a new programming language is by writing programs in it.', 'author': 'Dennis Ritchie'},
            {'text': 'Talk is cheap. Show me the code.', 'author': 'Linus Torvalds'},
            {'text': 'Programs must be written for people to read, and only incidentally for machines to execute.', 'author': 'Harold Abelson'},
            {'text': 'The function of good software is to make the complex appear to be simple.', 'author': 'Grady Booch'},
            {'text': 'Don\'t worry if it doesn\'t work right. If everything did, you\'d be out of a job.', 'author': 'Mosher\'s Law of Software Engineering'},
            {'text': 'Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.', 'author': 'Antoine de Saint-Exupery'},
            {'text': 'Good code is its own best documentation.', 'author': 'Steve McConnell'},
            {'text': 'The most disastrous thing that you can ever learn is your first programming language.', 'author': 'Alan Kay'},
            
            # Additional 270 quotes
            {'text': 'Innovation distinguishes between a leader and a follower.', 'author': 'Steve Jobs'},
            {'text': 'Technology is nothing. What\'s important is that you have a faith in people, that they\'re basically good and smart.', 'author': 'Steve Jobs'},
            {'text': 'Stay hungry, stay foolish.', 'author': 'Steve Jobs'},
            {'text': 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', 'author': 'Steve Jobs'},
            {'text': 'The way to get started is to quit talking and begin doing.', 'author': 'Walt Disney'},
            {'text': 'Success is not final, failure is not fatal: it is the courage to continue that counts.', 'author': 'Winston Churchill'},
            {'text': 'The future belongs to those who believe in the beauty of their dreams.', 'author': 'Eleanor Roosevelt'},
            {'text': 'It is during our darkest moments that we must focus to see the light.', 'author': 'Aristotle'},
            {'text': 'Life is what happens to you while you\'re busy making other plans.', 'author': 'John Lennon'},
            {'text': 'The purpose of our lives is to be happy.', 'author': 'Dalai Lama'},
            
            {'text': 'Clean code always looks like it was written by someone who cares.', 'author': 'Robert C. Martin'},
            {'text': 'Truth can only be found in one place: the code.', 'author': 'Robert C. Martin'},
            {'text': 'The only valid measurement of code quality: WTFs/minute.', 'author': 'Robert C. Martin'},
            {'text': 'Programming is the art of telling another human what one wants the computer to do.', 'author': 'Donald Knuth'},
            {'text': 'Premature optimization is the root of all evil.', 'author': 'Donald Knuth'},
            {'text': 'The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly.', 'author': 'Donald Knuth'},
            {'text': 'I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.', 'author': 'Bjarne Stroustrup'},
            {'text': 'C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do it blows your whole leg off.', 'author': 'Bjarne Stroustrup'},
            {'text': 'If you think it\'s simple, then you have misunderstood the problem.', 'author': 'Bjarne Stroustrup'},
            {'text': 'The most important single aspect of software development is to be clear about what you are trying to build.', 'author': 'Bjarne Stroustrup'},
            
            {'text': 'Walking on water and developing software from a specification are both easy if both are frozen.', 'author': 'Edward V Berard'},
            {'text': 'It\'s better to wait for a productive programmer to become available than it is to wait for the first available programmer to become productive.', 'author': 'Steve McConnell'},
            {'text': 'The trouble with programmers is that you can never tell what a programmer is doing until it\'s too late.', 'author': 'Seymour Cray'},
            {'text': 'Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.', 'author': 'Linus Torvalds'},
            {'text': 'Really, I\'m not out to destroy Microsoft. That will just be a completely unintentional side effect.', 'author': 'Linus Torvalds'},
            {'text': 'Software is like sex: it\'s better when it\'s free.', 'author': 'Linus Torvalds'},
            {'text': 'In real open source, you have the right to control your own destiny.', 'author': 'Linus Torvalds'},
            {'text': 'Intelligence is the ability to avoid doing work, yet getting the work done.', 'author': 'Linus Torvalds'},
            {'text': 'Bad programmers worry about the code. Good programmers worry about data structures and their relationships.', 'author': 'Linus Torvalds'},
            {'text': 'I\'m an egotistical bastard, and I name all my projects after myself. First Linux, now git.', 'author': 'Linus Torvalds'},
            
            {'text': 'The Internet? Is that thing still around?', 'author': 'Homer Simpson'},
            {'text': 'To err is human, but to really foul things up you need a computer.', 'author': 'Paul Ehrlich'},
            {'text': 'There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.', 'author': 'C.A.R. Hoare'},
            {'text': 'The unavoidable price of reliability is simplicity.', 'author': 'C.A.R. Hoare'},
            {'text': 'Inside every well-written large program is a well-written small program.', 'author': 'C.A.R. Hoare'},
            {'text': 'I call it my billion-dollar mistake... the invention of the null reference.', 'author': 'Tony Hoare'},
            {'text': 'The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times.', 'author': 'Donald Knuth'},
            {'text': 'Beware of bugs in the above code; I have only proved it correct, not tried it.', 'author': 'Donald Knuth'},
            {'text': 'Science is what we understand well enough to explain to a computer. Art is everything else we do.', 'author': 'Donald Knuth'},
            {'text': 'The computing scientist\'s main challenge is not to get confused by the complexities of his own making.', 'author': 'Edsger Dijkstra'},
            
            {'text': 'Simplicity is prerequisite for reliability.', 'author': 'Edsger Dijkstra'},
            {'text': 'Program testing can be used to show the presence of bugs, but never to show their absence.', 'author': 'Edsger Dijkstra'},
            {'text': 'The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.', 'author': 'Edsger Dijkstra'},
            {'text': 'Computer science is no more about computers than astronomy is about telescopes.', 'author': 'Edsger Dijkstra'},
            {'text': 'If debugging is the process of removing software bugs, then programming must be the process of putting them in.', 'author': 'Edsger Dijkstra'},
            {'text': 'The art of programming is the art of organizing complexity.', 'author': 'Edsger Dijkstra'},
            {'text': 'Elegance is not a dispensable luxury but a factor that decides between success and failure.', 'author': 'Edsger Dijkstra'},
            {'text': 'The use of COBOL cripples the mind; its teaching should, therefore, be regarded as a criminal offense.', 'author': 'Edsger Dijkstra'},
            {'text': 'Testing shows the presence, not the absence of bugs.', 'author': 'Edsger Dijkstra'},
            {'text': 'We must not forget that it is not our job to produce conforming products; it is our job to produce working programs.', 'author': 'Edsger Dijkstra'},
            
            {'text': 'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.', 'author': 'John Woods'},
            {'text': 'Any sufficiently advanced technology is indistinguishable from magic.', 'author': 'Arthur C. Clarke'},
            {'text': 'There are only 10 types of people in the world: those who understand binary and those who don\'t.', 'author': 'Anonymous'},
            {'text': '99 little bugs in the code, 99 little bugs. Take one down, patch it around, 117 little bugs in the code.', 'author': 'Anonymous'},
            {'text': 'A user interface is like a joke. If you have to explain it, it\'s not that good.', 'author': 'Martin LeBlanc'},
            {'text': 'Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots.', 'author': 'Rick Cook'},
            {'text': 'Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 'author': 'Bill Gates'},
            {'text': 'Your most unhappy customers are your greatest source of learning.', 'author': 'Bill Gates'},
            {'text': 'We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten.', 'author': 'Bill Gates'},
            {'text': 'Success is a lousy teacher. It seduces smart people into thinking they can\'t lose.', 'author': 'Bill Gates'},
            
            {'text': 'Optimism is an occupational hazard of programming; feedback is the treatment.', 'author': 'Kent Beck'},
            {'text': 'I\'m not a great programmer; I\'m just a good programmer with great habits.', 'author': 'Kent Beck'},
            {'text': 'Test-driven development is a way of managing fear during programming.', 'author': 'Kent Beck'},
            {'text': 'Listening, Testing, Coding, Designing. That\'s all there is to software. Anyone who tells you different is selling something.', 'author': 'Kent Beck'},
            {'text': 'Software development is a social activity.', 'author': 'Kent Beck'},
            {'text': 'The best thing about a boolean is even if you are wrong, you are only off by a bit.', 'author': 'Anonymous'},
            {'text': 'Without requirements or design, programming is the art of adding bugs to an empty text file.', 'author': 'Louis Srygley'},
            {'text': 'Before software can be reusable it first has to be usable.', 'author': 'Ralph Johnson'},
            {'text': 'A language that doesn\'t affect the way you think about programming is not worth knowing.', 'author': 'Alan Perlis'},
            {'text': 'The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.', 'author': 'Brian Kernighan'},
            
            {'text': 'Controlling complexity is the essence of computer programming.', 'author': 'Brian Kernighan'},
            {'text': 'Everyone knows that debugging is twice as hard as writing a program in the first place.', 'author': 'Brian Kernighan'},
            {'text': 'The most important thing in the programming language is the name. A language will not succeed without a good name.', 'author': 'Donald Knuth'},
            {'text': 'If you optimize everything, you will always be unhappy.', 'author': 'Donald Knuth'},
            {'text': 'Email is a wonderful thing for people whose role in life is to be on top of things. But not for me; my role is to be on the bottom of things.', 'author': 'Donald Knuth'},
            {'text': 'Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do.', 'author': 'Donald Knuth'},
            {'text': 'The real question is not whether machines think but whether men do.', 'author': 'B.F. Skinner'},
            {'text': 'That\'s the thing about people who think they hate computers. What they really hate is lousy programmers.', 'author': 'Larry Niven'},
            {'text': 'For a long time it puzzled me how something so expensive, so leading edge, could be so useless. And then it occurred to me that a computer is a stupid machine with the ability to do incredibly smart things, while computer programmers are smart people with the ability to do incredibly stupid things.', 'author': 'Bill Bryson'},
            {'text': 'The city\'s central computer told you? R2D2, you know better than to trust a strange computer!', 'author': 'C-3PO'},
            
            {'text': 'Computers are incredibly fast, accurate, and stupid. Human beings are incredibly slow, inaccurate, and brilliant.', 'author': 'Anonymous'},
            {'text': 'The good news about computers is that they do what you tell them to do. The bad news is that they do what you tell them to do.', 'author': 'Ted Nelson'},
            {'text': 'Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.', 'author': 'Alan Kay'},
            {'text': 'A programming language is low level when its programs require attention to the irrelevant.', 'author': 'Alan Perlis'},
            {'text': 'Lisp isn\'t a language, it\'s a building material.', 'author': 'Alan Kay'},
            {'text': 'The best way to prepare for life is to begin to live.', 'author': 'Elbert Hubbard'},
            {'text': 'Object-oriented programming is an exceptionally bad idea which could only have originated in California.', 'author': 'Edsger Dijkstra'},
            {'text': 'When we had no computers, we had no programming problem either.', 'author': 'Edsger Dijkstra'},
            {'text': 'Don\'t comment bad code—rewrite it.', 'author': 'Brian Kernighan'},
            {'text': 'Deleted code is debugged code.', 'author': 'Jeff Sickel'},
            
            {'text': 'If debugging is the process of removing bugs, then programming must be the process of putting them in.', 'author': 'Sam Redwine'},
            {'text': 'The most likely way for the world to be destroyed, most experts agree, is by accident. That\'s where we come in; we\'re computer professionals. We cause accidents.', 'author': 'Nathaniel Borenstein'},
            {'text': 'It has been said that the great scientific disciplines are examples of giants standing on the shoulders of other giants. It has also been said that the software industry is an example of midgets standing on the toes of other midgets.', 'author': 'Alan Cooper'},
            {'text': 'The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.', 'author': 'Tom Cargill'},
            {'text': 'In software, we rarely have meaningful requirements. Even if we do, the only measure of success that matters is whether our solution solves the customer\'s shifting idea of what their problem is.', 'author': 'Jeff Atwood'},
            {'text': 'No one in the brief history of computing has ever written a piece of perfect software. It\'s unlikely that you\'ll be the first.', 'author': 'Andy Hunt'},
            {'text': 'One of the best programming skills you can have is knowing when to walk away for awhile.', 'author': 'Oscar Godson'},
            {'text': 'Learning to code is useful no matter what your career ambitions are.', 'author': 'Arianna Huffington'},
            {'text': 'The value of a prototype is in the education it gives you, not in the code itself.', 'author': 'Alan Cooper'},
            {'text': 'Fix the cause, not the symptom.', 'author': 'Steve Maguire'},
            
            {'text': 'Simplicity is the soul of efficiency.', 'author': 'Austin Freeman'},
            {'text': 'Before you finish eating breakfast in the morning, you\'ve depended on more than half the world.', 'author': 'Martin Luther King Jr.'},
            {'text': 'The best time to plant a tree was 20 years ago. The second best time is now.', 'author': 'Chinese Proverb'},
            {'text': 'It does not matter how slowly you go as long as you do not stop.', 'author': 'Confucius'},
            {'text': 'Don\'t be afraid to give up the good to go for the great.', 'author': 'John D. Rockefeller'},
            {'text': 'The only impossible journey is the one you never begin.', 'author': 'Tony Robbins'},
            {'text': 'In the middle of difficulty lies opportunity.', 'author': 'Albert Einstein'},
            {'text': 'It is better to fail in originality than to succeed in imitation.', 'author': 'Herman Melville'},
            {'text': 'Success is not how high you have climbed, but how you make a positive difference to the world.', 'author': 'Roy T. Bennett'},
            {'text': 'Don\'t let yesterday take up too much of today.', 'author': 'Will Rogers'},
            
            {'text': 'You learn more from failure than from success. Don\'t let it stop you. Failure builds character.', 'author': 'Unknown'},
            {'text': 'If you are working on something that you really care about, you don\'t have to be pushed. The vision pulls you.', 'author': 'Steve Jobs'},
            {'text': 'People who are crazy enough to think they can change the world, are the ones who do.', 'author': 'Rob Siltanen'},
            {'text': 'Believe you can and you\'re halfway there.', 'author': 'Theodore Roosevelt'},
            {'text': 'When you have a dream, you\'ve got to grab it and never let go.', 'author': 'Carol Burnett'},
            {'text': 'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination.', 'author': 'Jimmy Dean'},
            {'text': 'No matter what you\'re going through, there\'s a light at the end of the tunnel.', 'author': 'Demi Lovato'},
            {'text': 'Life is like riding a bicycle. To keep your balance, you must keep moving.', 'author': 'Albert Einstein'},
            {'text': 'You are never too old to set another goal or to dream a new dream.', 'author': 'Malala Yousafzai'},
            {'text': 'At the end of the day, whether or not those people are comfortable with how you\'re living your life doesn\'t matter. What matters is whether you\'re comfortable with it.', 'author': 'Dr. Phil'},
            
            {'text': 'People begin to become successful the minute they decide to be.', 'author': 'Harvey MacKay'},
            {'text': 'The way to get started is to quit talking and begin doing.', 'author': 'Walt Disney'},
            {'text': 'Don\'t limit yourself. Many people limit themselves to what they think they can do.', 'author': 'Mary Kay Ash'},
            {'text': 'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.', 'author': 'Winston Churchill'},
            {'text': 'Don\'t say you don\'t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo Da Vinci, Thomas Jefferson, and Albert Einstein.', 'author': 'H. Jackson Brown Jr.'},
            {'text': 'Within our dreams and aspirations we find our opportunities.', 'author': 'Sue Atchley Ebaugh'},
            {'text': 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', 'author': 'David Brinkley'},
            {'text': 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'author': 'Roy T. Bennett'},
            {'text': 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'author': 'Ralph Waldo Emerson'},
            {'text': 'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.', 'author': 'Chantal Sutherland'},
            
            {'text': 'Programming is like writing a book... except if you miss a single comma on page 126, the whole thing makes no sense.', 'author': 'Anonymous'},
            {'text': 'Why do programmers prefer dark mode? Because light attracts bugs!', 'author': 'Anonymous'},
            {'text': 'A SQL query goes into a bar, walks up to two tables and asks: \'Can I join you?\'', 'author': 'Anonymous'},
            {'text': 'How many programmers does it take to change a light bulb? None – that\'s a hardware problem.', 'author': 'Anonymous'},
            {'text': 'I would love to change the world, but they won\'t give me the source code.', 'author': 'Anonymous'},
            {'text': 'There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.', 'author': 'Phil Karlton'},
            {'text': 'I have not failed. I\'ve just found 10,000 ways that won\'t work.', 'author': 'Thomas Edison'},
            {'text': 'A ship in port is safe, but that\'s not what ships are built for.', 'author': 'Grace Hopper'},
            {'text': 'The most dangerous phrase in the language is: \'We\'ve always done it this way.\'', 'author': 'Grace Hopper'},
            {'text': 'Humans are allergic to change. They love to say: \'We\'ve always done it this way.\' I try to fight that.', 'author': 'Grace Hopper'},
            
            {'text': 'Leadership is about making others better as a result of your presence and making sure that impact lasts in your absence.', 'author': 'Sheryl Sandberg'},
            {'text': 'The question isn\'t who is going to let me; it\'s who is going to stop me.', 'author': 'Ayn Rand'},
            {'text': 'What you do today can improve all your tomorrows.', 'author': 'Ralph Marston'},
            {'text': 'The only person you are destined to become is the person you decide to be.', 'author': 'Ralph Waldo Emerson'},
            {'text': 'Go confidently in the direction of your dreams. Live the life you have imagined.', 'author': 'Henry David Thoreau'},
            {'text': 'When I was 5 years old, my mother always told me that happiness was the key to life.', 'author': 'John Lennon'},
            {'text': 'Fall seven times and stand up eight.', 'author': 'Japanese Proverb'},
            {'text': 'When one door of happiness closes, another opens.', 'author': 'Helen Keller'},
            {'text': 'Everything has beauty, but not everyone can see.', 'author': 'Confucius'},
            {'text': 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', 'author': 'Anne Frank'},
            
            {'text': 'When I let go of what I am, I become what I might be.', 'author': 'Lao Tzu'},
            {'text': 'Everything you\'ve ever wanted is on the other side of fear.', 'author': 'George Addair'},
            {'text': 'We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.', 'author': 'Plato'},
            {'text': 'Teach thy tongue to say, \'I do not know,\' and thous shalt progress.', 'author': 'Maimonides'},
            {'text': 'Start where you are. Use what you have. Do what you can.', 'author': 'Arthur Ashe'},
            {'text': 'When I dare to be powerful – to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.', 'author': 'Audre Lorde'},
            {'text': 'The most common way people give up their power is by thinking they don\'t have any.', 'author': 'Alice Walker'},
            {'text': 'If you look at what you have in life, you\'ll always have more.', 'author': 'Oprah Winfrey'},
            {'text': 'If you do what you\'ve always done, you\'ll get what you\'ve always gotten.', 'author': 'Tony Robbins'},
            {'text': 'Dreaming, after all, is a form of planning.', 'author': 'Gloria Steinem'},
            
            {'text': 'It\'s your place in the world; it\'s your life. Go on and do all you can with it, and make it the life you want to live.', 'author': 'Mae Jemison'},
            {'text': 'You may be disappointed if you fail, but you are doomed if you don\'t try.', 'author': 'Beverly Sills'},
            {'text': 'Remember no one can make you feel inferior without your consent.', 'author': 'Eleanor Roosevelt'},
            {'text': 'Life is what we make it, always has been, always will be.', 'author': 'Grandma Moses'},
            {'text': 'The question isn\'t who is going to let me; it\'s who is going to stop me.', 'author': 'Ayn Rand'},
            {'text': 'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.', 'author': 'Henry Ford'},
            {'text': 'It\'s not whether you get knocked down; it\'s whether you get up.', 'author': 'Vince Lombardi'},
            {'text': 'If you want to lift yourself up, lift up someone else.', 'author': 'Booker T. Washington'},
            {'text': 'Champions keep playing until they get it right.', 'author': 'Billie Jean King'},
            {'text': 'Failure is the condiment that gives success its flavor.', 'author': 'Truman Capote'},
            
            {'text': 'Don\'t watch the clock; do what it does. Keep going.', 'author': 'Sam Levenson'},
            {'text': 'A year from now you may wish you had started today.', 'author': 'Karen Lamb'},
            {'text': 'You don\'t have to be great to get started, but you have to get started to be great.', 'author': 'Les Brown'},
            {'text': 'A smart person learns from his mistakes, but a truly wise person learns from the mistakes of others.', 'author': 'Ken Schramm'},
            {'text': 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', 'author': 'Thomas Edison'},
            {'text': 'Don\'t be afraid to give something up for something better.', 'author': 'John Spence'},
            {'text': 'You can\'t use up creativity. The more you use, the more you have.', 'author': 'Maya Angelou'},
            {'text': 'Dream big and dare to fail.', 'author': 'Norman Vaughan'},
            {'text': 'Our lives begin to end the day we become silent about things that matter.', 'author': 'Martin Luther King Jr.'},
            {'text': 'Do what you can, where you are, with what you have.', 'author': 'Teddy Roosevelt'},
            
            {'text': 'If you want something you\'ve never had, you must be willing to do something you\'ve never done.', 'author': 'Thomas Jefferson'},
            {'text': 'Success is getting what you want, happiness is wanting what you get.', 'author': 'W.P. Kinsella'},
            {'text': 'As we look ahead into the next century, leaders will be those who empower others.', 'author': 'Bill Gates'},
            {'text': 'A person who never made a mistake never tried anything new.', 'author': 'Albert Einstein'},
            {'text': 'The person who says it cannot be done should not interrupt the person who is doing it.', 'author': 'Chinese Proverb'},
            {'text': 'There are no traffic jams along the extra mile.', 'author': 'Roger Staubach'},
            {'text': 'It is never too late to be what you might have been.', 'author': 'George Eliot'},
            {'text': 'You become what you believe.', 'author': 'Oprah Winfrey'},
            {'text': 'I would rather die of passion than of boredom.', 'author': 'Vincent van Gogh'},
            {'text': 'A truly rich man is one whose children run into his arms when his hands are empty.', 'author': 'Unknown'},
            
            {'text': 'It is impossible for a man to learn what he thinks he already knows.', 'author': 'Epictetus'},
            {'text': 'Either write something worth reading or do something worth writing.', 'author': 'Benjamin Franklin'},
            {'text': 'Nothing is impossible, the word itself says, \'I\'m possible\'!', 'author': 'Audrey Hepburn'},
            {'text': 'The only way to do great work is to love what you do.', 'author': 'Steve Jobs'},
            {'text': 'If you can dream it, you can achieve it.', 'author': 'Zig Ziglar'},
            {'text': 'The future belongs to those who believe in the beauty of their dreams.', 'author': 'Eleanor Roosevelt'},
            {'text': 'It is during our darkest moments that we must focus to see the light.', 'author': 'Aristotle Onassis'},
            {'text': 'Whoever is happy will make others happy too.', 'author': 'Anne Frank'},
            {'text': 'Do not go where the path may lead, go instead where there is no path and leave a trail.', 'author': 'Ralph Waldo Emerson'},
            {'text': 'Programming is not a science. Programming is a craft.', 'author': 'Richard Stallman'}
        ]

        created_count = 0
        for quote_data in sample_quotes:
            quote, created = Quote.objects.get_or_create(
                text=quote_data['text'],
                defaults={
                    'author': quote_data['author'],
                    'submitted_by': admin_user,
                    'is_approved': True
                }
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(f'Successfully created {created_count} sample quotes')
        )
