# Generated by Django 5.2.5 on 2025-08-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_encouragement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this quote was approved', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this quote is approved for display'),
        ),
    ]
